Implement API to drain a specific worker
TraceMachina/native-link pull request #413
Opened 2023-11-21 22:26 UTC by steed924

# Description

It implements an API to drain a specific worker.
It currently simply acts like pausing the worker and clearing existing running actions.

Fixes #351 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
  not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

## Checklist

- [ ] Updated documentation if needed
- [ ] Tests added/amended
- [x] `bazel test //...`  passes locally
- [x] PR is contained in a single commit, using `git amend` see some [docs](https://www.atlassian.com/git/tutorials/rewriting-history)

2023-11-22 15:33 UTC, allada requested changes
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/native-link/413)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @steed924)

___
*[`cas/scheduler/worker.rs` line 76 at r1](https://reviewable.io/reviews/TraceMachina/native-link/413#-NjrdUwi9fbs_qp2EpGJ:-NjrdUwj8JyQH2Mio2zK:b4pmurj) ([raw file](https://github.com/TraceMachina/native-link/blob/9702967e1a250fab6038d6e3382efd400cf0c079/cas/scheduler/worker.rs#L76)):*
> ```XML
> 
>     /// Request that the worker is drained and stops accepting new jobs.
>     Drain,
> ```

This API should probably be a REST api for the scheduler. Doing this on the Worker->scheduler channel seems like it'll be very difficult to work with.

The rest api should allow anyone on the admin endpoint to drain any worker. The use case is to have an AWS lambda decided to drop specific workers, drain them first then terminate them.

I would make a new service called "admin_service" or something similar in the config & wire it up in the cas_main.rs file.


<!-- Sent from Reviewable.io -->

2023-11-22 17:42 UTC, steed924 reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/native-link/413)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @allada)

___
*[`cas/scheduler/worker.rs` line 76 at r1](https://reviewable.io/reviews/TraceMachina/native-link/413#-NjrdUwi9fbs_qp2EpGJ:-Njs6trx2uqHw0pXNV26:bb6scqz) ([raw file](https://github.com/TraceMachina/native-link/blob/9702967e1a250fab6038d6e3382efd400cf0c079/cas/scheduler/worker.rs#L76)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

This API should probably be a REST api for the scheduler. Doing this on the Worker->scheduler channel seems like it'll be very difficult to work with.

The rest api should allow anyone on the admin endpoint to drain any worker. The use case is to have an AWS lambda decided to drop specific workers, drain them first then terminate them.

I would make a new service called "admin_service" or something similar in the config & wire it up in the cas_main.rs file.
</blockquote></details>

Thanks for your review, @allada. Sure, it makes sense to me.


<!-- Sent from Reviewable.io -->

2023-11-29 23:25 UTC, allada requested changes
> Reviewed 6 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/native-link/413)* status: 6 of 10 files reviewed, 13 unresolved discussions (waiting on @steed924)

___
*[`native-link-config/src/cas_server.rs` line 165 at r3](https://reviewable.io/reviews/TraceMachina/native-link/413#-NkSC1t91Uwajdx_Erj6:-NkSC1t91Uwajdx_Erj7:bejbc4o) ([raw file](https://github.com/TraceMachina/native-link/blob/bd9c1907204ee2b7d574d006088712d0fe83e077/native-link-config/src/cas_server.rs#L165)):*
> ```XML
>     /// The scheduler name referenced in the `schedulers` map in the main config.
>     #[serde(deserialize_with = "convert_string_with_shellexpand")]
>     pub scheduler: SchedulerRefName,
> ```

nit: Let's remove this completely and admin requests will just have unrestricted access to everything. We can add it later if we find out users want restricted variations.
___
*[`native-link-config/src/cas_server.rs` line 208 at r3](https://reviewable.io/reviews/TraceMachina/native-link/413#-NkS87kY1mQbMC_3fhsH:-NkS87kY1mQbMC_3fhsI:b-za2fig) ([raw file](https://github.com/TraceMachina/native-link/blob/bd9c1907204ee2b7d574d006088712d0fe83e077/native-link-config/src/cas_server.rs#L208)):*
> ```XML
>     pub prometheus: Option<PrometheusConfig>,
> 
>     /// This is the service for managing workers in the scheduler.
> ```

nit: Lets reword this to not be specific to scheduler and instead let it support any administrative tasks.
___
*[`native-link-config/src/cas_server.rs` line 210 at r3](https://reviewable.io/reviews/TraceMachina/native-link/413#-NkS8HwF35DtdXQHYw3O:-NkS8HwF35DtdXQHYw3P:b6bd7ak) ([raw file](https://github.com/TraceMachina/native-link/blob/bd9c1907204ee2b7d574d006088712d0fe83e077/native-link-config/src/cas_server.rs#L210)):*
> ```XML
>     /// This is the service for managing workers in the scheduler.
>     /// It provides a REST API endpoint for administrative purposes.
>     /// For example, we will use this API to drain a specific worker from the
> ```

nit: No need for example here.
___
*[`native-link-scheduler/src/simple_scheduler.rs` line 392 at r3](https://reviewable.io/reviews/TraceMachina/native-link/413#-NkSOMNF9evUkY5hvP9-:-NkSOMNF9evUkY5hvP90:bcpv7vh) ([raw file](https://github.com/TraceMachina/native-link/blob/bd9c1907204ee2b7d574d006088712d0fe83e077/native-link-scheduler/src/simple_scheduler.rs#L392)):*
> ```XML
>         if let Some(worker) = self.workers.workers.get_mut(worker_id) {
>             self.metrics.workers_drained.inc();
>             worker.is_paused = true;
> ```

Lets create a new property called `is_draining` and flag it. Then in all places we use `is_paused` turn it into a function called something like `.can_accept_work()` and check both values.
___
*[`native-link-scheduler/src/simple_scheduler.rs` line 395 at r3](https://reviewable.io/reviews/TraceMachina/native-link/413#-NkSERXzC8tkzRtHSMBr:-NkSERXzC8tkzRtHSMBs:b-kpdaxm) ([raw file](https://github.com/TraceMachina/native-link/blob/bd9c1907204ee2b7d574d006088712d0fe83e077/native-link-scheduler/src/simple_scheduler.rs#L395)):*
> ```XML
>             // We create a temporary Vec to avoid doubt about a possible code
>             // path touching the worker.running_action_infos elsewhere.
>             let running_action_infos = worker.running_action_infos.drain().collect::<Vec<_>>();
> ```

Lets not do this. We want any outstanding actions to finish.
___
*[`src/bin/cas.rs` line 398 at r3](https://reviewable.io/reviews/TraceMachina/native-link/413#-NkSCraM8izvRbnRMA0O:-NkSCraN77YD077Fk3rH:bv4xdlv) ([raw file](https://github.com/TraceMachina/native-link/blob/bd9c1907204ee2b7d574d006088712d0fe83e077/src/bin/cas.rs#L398)):*
> ```XML
> 
>         if let Some(admin_config) = services.admin {
>             fn error_to_response<E: std::error::Error>(e: E) -> hyper::Response<Body> {
> ```

nit: inline this.
___
*[`src/bin/cas.rs` line 404 at r3](https://reviewable.io/reviews/TraceMachina/native-link/413#-NkSCNRG198qVopufP4r:-NkSCNRG198qVopufP4s:bcwdf0h) ([raw file](https://github.com/TraceMachina/native-link/blob/bd9c1907204ee2b7d574d006088712d0fe83e077/src/bin/cas.rs#L404)):*
> ```XML
>                     .unwrap()
>             }
>             let path = if admin_config.path.is_empty() {
> ```

nit: 
```rs
let path = admin_config.path.unwrap_or_else(|| DEFAULT_ADMIN_API_PATH.into());
```
___
*[`src/bin/cas.rs` line 418 at r3](https://reviewable.io/reviews/TraceMachina/native-link/413#-NkSDOqv6IfyEkU6ZS_H:-NkSDOqv6IfyEkU6ZS_I:b-wp4nsq) ([raw file](https://github.com/TraceMachina/native-link/blob/bd9c1907204ee2b7d574d006088712d0fe83e077/src/bin/cas.rs#L418)):*
> ```XML
>                 }).unwrap()
>                 .clone());
>             // Build a nested admin API.
> ```

nit: Needless comment.
___
*[`src/bin/cas.rs` line 422 at r3](https://reviewable.io/reviews/TraceMachina/native-link/413#-NkSBdaW8R-kmIGpEQLJ:-NkSBdaW8R-kmIGpEQLK:b-1zv3rg) ([raw file](https://github.com/TraceMachina/native-link/blob/bd9c1907204ee2b7d574d006088712d0fe83e077/src/bin/cas.rs#L422)):*
> ```XML
>                 path,
>                 Router::new().route(
>                     "/drain/:worker_id",
> ```

nit: Let's use `/scheduler/{:instance_name}/drain/{:worker_id}` and lookup each scheduler on each request.
___
*[`src/bin/cas.rs` line 427 at r3](https://reviewable.io/reviews/TraceMachina/native-link/413#-NkSDL4dAlqnPps6S62B:-NkSDL4dAlqnPps6S62C:bxurbyb) ([raw file](https://github.com/TraceMachina/native-link/blob/bd9c1907204ee2b7d574d006088712d0fe83e077/src/bin/cas.rs#L427)):*
> ```XML
>                         async move {
>                             spawn_blocking(move || {
>                                 let worker_id = WorkerId(worker_id);
> ```

nit: Inline this.
___
*[`src/bin/cas.rs` line 428 at r3](https://reviewable.io/reviews/TraceMachina/native-link/413#-NkSDGy_2QA9kARyfOvU:-NkSDGy_2QA9kARyfOvV:bjxv1e2) ([raw file](https://github.com/TraceMachina/native-link/blob/bd9c1907204ee2b7d574d006088712d0fe83e077/src/bin/cas.rs#L428)):*
> ```XML
>                             spawn_blocking(move || {
>                                 let worker_id = WorkerId(worker_id);
>                                 let _ = scheduler.drain_worker(worker_id);
> ```

nit: Handle error and propagate it up into a 500 error.
___
*[`src/bin/cas.rs` line 434 at r3](https://reviewable.io/reviews/TraceMachina/native-link/413#-NkSD4Og4nIaVoJkCFZ3:-NkSD4Og4nIaVoJkCFZ4:b-ld2rya) ([raw file](https://github.com/TraceMachina/native-link/blob/bd9c1907204ee2b7d574d006088712d0fe83e077/src/bin/cas.rs#L434)):*
> ```XML
>                                         "text/plain; version=0.0.4; charset=utf-8",
>                                     )
>                                     .body(Body::from(format!("Worker {} is drained", worker_id)))
> ```

nit: `format!("Draining worker {worker_id}");`
___
*[`src/bin/cas.rs` line 435 at r3](https://reviewable.io/reviews/TraceMachina/native-link/413#-NkSD-CQCr1SGjMxfSXE:-NkSD-CQCr1SGjMxfSXF:b-c4oyfo) ([raw file](https://github.com/TraceMachina/native-link/blob/bd9c1907204ee2b7d574d006088712d0fe83e077/src/bin/cas.rs#L435)):*
> ```XML
>                                     )
>                                     .body(Body::from(format!("Worker {} is drained", worker_id)))
>                                     .unwrap()
> ```

nit: Don't use `.unwrap()` use `.err_tip()` or `.map_err()`.


<!-- Sent from Reviewable.io -->

2023-11-29 23:28 UTC, allada requested changes
Looks mostly good, just a few changes.

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/native-link/413#-:-NkSPI5e1QzLCe-1_Xc2:b-ti3wyy)* status: 6 of 10 files reviewed, 15 unresolved discussions (waiting on @steed924)

*[a discussion](https://reviewable.io/reviews/TraceMachina/native-link/413#-NkSPM2Z-zZ1d0_Jl14Y:-NkSPM2Z-zZ1d0_Jl14Z:bfscx6w) (no related file):*
Please also write a test for this functionality.

___
___
*[`native-link-scheduler/src/simple_scheduler.rs` line 389 at r3](https://reviewable.io/reviews/TraceMachina/native-link/413#-NkSP5cX0QKyMdhZXOiY:-NkSP5cX0QKyMdhZXOiZ:bry4np6) ([raw file](https://github.com/TraceMachina/native-link/blob/bd9c1907204ee2b7d574d006088712d0fe83e077/native-link-scheduler/src/simple_scheduler.rs#L389)):*
> ```XML
> 
>     /// Drains the worker in the pool and puts items back into the queue if anything was being executed on it.
>     fn drain_worker(&mut self, worker_id: &WorkerId, err: Error) {
> ```

nit: Have this take a `WorkerId` instead of ref to one.


<!-- Sent from Reviewable.io -->

2023-12-01 00:03 UTC, steed924 reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/native-link/413)* status: 5 of 16 files reviewed, 6 unresolved discussions (waiting on @allada)

___
*[`native-link-config/src/cas_server.rs` line 165 at r3](https://reviewable.io/reviews/TraceMachina/native-link/413#-NkSC1t91Uwajdx_Erj6:-NkXf80M57UYwJq0T5uN:bb6un1j) ([raw file](https://github.com/TraceMachina/native-link/blob/bd9c1907204ee2b7d574d006088712d0fe83e077/native-link-config/src/cas_server.rs#L165)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Let's remove this completely and admin requests will just have unrestricted access to everything. We can add it later if we find out users want restricted variations.
</blockquote></details>

Done
___
*[`native-link-config/src/cas_server.rs` line 208 at r3](https://reviewable.io/reviews/TraceMachina/native-link/413#-NkS87kY1mQbMC_3fhsH:-NkXfAJmCnBml6muMHmi:bb6un1j) ([raw file](https://github.com/TraceMachina/native-link/blob/bd9c1907204ee2b7d574d006088712d0fe83e077/native-link-config/src/cas_server.rs#L208)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Lets reword this to not be specific to scheduler and instead let it support any administrative tasks.
</blockquote></details>

Done
___
*[`native-link-config/src/cas_server.rs` line 210 at r3](https://reviewable.io/reviews/TraceMachina/native-link/413#-NkS8HwF35DtdXQHYw3O:-NkXfBWJ2LyjdlZDVVLO:bb6un1j) ([raw file](https://github.com/TraceMachina/native-link/blob/bd9c1907204ee2b7d574d006088712d0fe83e077/native-link-config/src/cas_server.rs#L210)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: No need for example here.
</blockquote></details>

Done
___
*[`native-link-scheduler/src/simple_scheduler.rs` line 389 at r3](https://reviewable.io/reviews/TraceMachina/native-link/413#-NkSP5cX0QKyMdhZXOiY:-NkXfEyaDC7zjLlDW0H3:bb6un1j) ([raw file](https://github.com/TraceMachina/native-link/blob/bd9c1907204ee2b7d574d006088712d0fe83e077/native-link-scheduler/src/simple_scheduler.rs#L389)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Have this take a `WorkerId` instead of ref to one.
</blockquote></details>

Done
___
*[`native-link-scheduler/src/simple_scheduler.rs` line 395 at r3](https://reviewable.io/reviews/TraceMachina/native-link/413#-NkSERXzC8tkzRtHSMBr:-NkXfFwrC7aGG8wRjg1-:bb6un1j) ([raw file](https://github.com/TraceMachina/native-link/blob/bd9c1907204ee2b7d574d006088712d0fe83e077/native-link-scheduler/src/simple_scheduler.rs#L395)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

Lets not do this. We want any outstanding actions to finish.
</blockquote></details>

Done
___
*[`src/bin/cas.rs` line 398 at r3](https://reviewable.io/reviews/TraceMachina/native-link/413#-NkSCraM8izvRbnRMA0O:-NkXfJbs2Tir3dINVB7b:bb6un1j) ([raw file](https://github.com/TraceMachina/native-link/blob/bd9c1907204ee2b7d574d006088712d0fe83e077/src/bin/cas.rs#L398)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: inline this.
</blockquote></details>

Done
___
*[`src/bin/cas.rs` line 404 at r3](https://reviewable.io/reviews/TraceMachina/native-link/413#-NkSCNRG198qVopufP4r:-NkXfKdXBvrmFKHQca_V:br1mgv3) ([raw file](https://github.com/TraceMachina/native-link/blob/bd9c1907204ee2b7d574d006088712d0fe83e077/src/bin/cas.rs#L404)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: 
```rs
let path = admin_config.path.unwrap_or_else(|| DEFAULT_ADMIN_API_PATH.into());
```
</blockquote></details>

It can't be done with `unwrap_or_else()` because `admin_config.path` is `String` not `Result` or `Option`. It has a default value of "" in case it hasn't set in the json file. So I need to use only if-else statement.
___
*[`src/bin/cas.rs` line 418 at r3](https://reviewable.io/reviews/TraceMachina/native-link/413#-NkSDOqv6IfyEkU6ZS_H:-NkXfgQX6oWJmiMvLjO9:bb6un1j) ([raw file](https://github.com/TraceMachina/native-link/blob/bd9c1907204ee2b7d574d006088712d0fe83e077/src/bin/cas.rs#L418)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Needless comment.
</blockquote></details>

Done
___
*[`src/bin/cas.rs` line 422 at r3](https://reviewable.io/reviews/TraceMachina/native-link/413#-NkSBdaW8R-kmIGpEQLJ:-NkXfhLM9XNtb29Nv-bM:bb6un1j) ([raw file](https://github.com/TraceMachina/native-link/blob/bd9c1907204ee2b7d574d006088712d0fe83e077/src/bin/cas.rs#L422)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Let's use `/scheduler/{:instance_name}/drain/{:worker_id}` and lookup each scheduler on each request.
</blockquote></details>

Done
___
*[`src/bin/cas.rs` line 427 at r3](https://reviewable.io/reviews/TraceMachina/native-link/413#-NkSDL4dAlqnPps6S62B:-NkXfi9o27i3fGXGnUUC:bb6un1j) ([raw file](https://github.com/TraceMachina/native-link/blob/bd9c1907204ee2b7d574d006088712d0fe83e077/src/bin/cas.rs#L427)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Inline this.
</blockquote></details>

Done
___
*[`src/bin/cas.rs` line 434 at r3](https://reviewable.io/reviews/TraceMachina/native-link/413#-NkSD4Og4nIaVoJkCFZ3:-NkXfoB5AaNARHd3f2Vv:bb6un1j) ([raw file](https://github.com/TraceMachina/native-link/blob/bd9c1907204ee2b7d574d006088712d0fe83e077/src/bin/cas.rs#L434)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: `format!("Draining worker {worker_id}");`
</blockquote></details>

Done
___
*[`src/bin/cas.rs` line 435 at r3](https://reviewable.io/reviews/TraceMachina/native-link/413#-NkSD-CQCr1SGjMxfSXE:-NkXfpR34-jRdG7TAz1S:b-896fix) ([raw file](https://github.com/TraceMachina/native-link/blob/bd9c1907204ee2b7d574d006088712d0fe83e077/src/bin/cas.rs#L435)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Don't use `.unwrap()` use `.err_tip()` or `.map_err()`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-12-01 11:33 UTC, steed924 reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/native-link/413)* status: 5 of 16 files reviewed, 6 unresolved discussions (waiting on @allada)

___
*[`native-link-scheduler/src/simple_scheduler.rs` line 392 at r3](https://reviewable.io/reviews/TraceMachina/native-link/413#-NkSOMNF9evUkY5hvP9-:-Nk_8jdH1UEB-OxaoWK3:bb6un1j) ([raw file](https://github.com/TraceMachina/native-link/blob/bd9c1907204ee2b7d574d006088712d0fe83e077/native-link-scheduler/src/simple_scheduler.rs#L392)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

Lets create a new property called `is_draining` and flag it. Then in all places we use `is_paused` turn it into a function called something like `.can_accept_work()` and check both values.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-12-01 15:47 UTC, steed924 reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/native-link/413)* status: 5 of 16 files reviewed, 6 unresolved discussions (waiting on @allada)

___
*[`src/bin/cas.rs` line 428 at r3](https://reviewable.io/reviews/TraceMachina/native-link/413#-NkSDGy_2QA9kARyfOvU:-Nka2IYB0uXpWox2NnNY:bb6un1j) ([raw file](https://github.com/TraceMachina/native-link/blob/bd9c1907204ee2b7d574d006088712d0fe83e077/src/bin/cas.rs#L428)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Handle error and propagate it up into a 500 error.
</blockquote></details>

Done
___
*[`src/bin/cas.rs` line 430 at r5](https://reviewable.io/reviews/TraceMachina/native-link/413#-Nka2cys5xoNKO_H1Bal:-Nka2cys5xoNKO_H1Bam:b1x01ee) ([raw file](https://github.com/TraceMachina/native-link/blob/d0f44b31d17a2e5a61c8a73c3e617f3c089899c1/src/bin/cas.rs#L430)):*
> ```XML
>                                         )
>                                         .body(Body::from(format!("Draining worker {worker_id}")))
>                                         .unwrap()
> ```

The reason I use unwrap()  here is because the post handler needs to return Response, not Result type.
That unwrap() is from Response::builder() and it won't cause a panic in normal cases I think.
Anyhow, I hope to have a great solution to handle this properly.

I handled other errors and made them to be returned in 500 error.


<!-- Sent from Reviewable.io -->

2023-12-01 15:47 UTC, steed924 reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/native-link/413)* status: 5 of 16 files reviewed, 6 unresolved discussions (waiting on @allada)

*[a discussion](https://reviewable.io/reviews/TraceMachina/native-link/413#-NkSPM2Z-zZ1d0_Jl14Y:-Nka33dX7ao-siX-RUT3:b-896fix) (no related file):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

Please also write a test for this functionality.
</blockquote></details>

Done.

___


<!-- Sent from Reviewable.io -->

2023-12-01 16:30 UTC, allada requested changes
> Reviewed 3 of 10 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/native-link/413)* status: 7 of 16 files reviewed, 12 unresolved discussions (waiting on @steed924)

___
*[`error/src/lib.rs` line 214 at r5](https://reviewable.io/reviews/TraceMachina/native-link/413#-NkaA1PJ3BvJhCTjHNGc:-NkaA1PJ3BvJhCTjHNGd:b-jjgrdf) ([raw file](https://github.com/TraceMachina/native-link/blob/d0f44b31d17a2e5a61c8a73c3e617f3c089899c1/error/src/lib.rs#L214)):*
> ```XML
> }
> 
> impl From<axum::http::Error> for Error {
> ```

nit: I'd rather not force everyone that uses `error` to depend on `axum`. Can we just inline this for the rare edge cases instead?
___
*[`native-link-scheduler/src/simple_scheduler.rs` line 390 at r5](https://reviewable.io/reviews/TraceMachina/native-link/413#-NkaAL8E3Osx50OjD0Qi:-NkaAL8F9wuaaoOAq_Z1:bdiru21) ([raw file](https://github.com/TraceMachina/native-link/blob/d0f44b31d17a2e5a61c8a73c3e617f3c089899c1/native-link-scheduler/src/simple_scheduler.rs#L390)):*
> ```XML
>     /// Drains the worker in the pool and puts items back into the queue if anything was being executed on it.
>     fn drain_worker(&mut self, worker_id: WorkerId) -> Result<(), Error> {
>         if let Some(worker) = self.workers.workers.get_mut(&worker_id) {
> ```

nit This can be greatly simplified to:
```rs
let worker = self.workers.workers
  .get_mut(&worker_id)
  .err_tip(|| format!("Worker {worker_id} doesn't exist in the pool"))?;
self.metrics.workers_drained.inc();
worker.is_draining = true;
self.tasks_or_workers_change_notify.notify_one();
Ok(())
```
___
*[`native-link-scheduler/src/simple_scheduler.rs` line 695 at r5](https://reviewable.io/reviews/TraceMachina/native-link/413#-Nka63au6VDQPqFzUiJ-:-Nka63au6VDQPqFzUiJ0:bvdwhkl) ([raw file](https://github.com/TraceMachina/native-link/blob/d0f44b31d17a2e5a61c8a73c3e617f3c089899c1/native-link-scheduler/src/simple_scheduler.rs#L695)):*
> ```XML
> 
>     /// Checks to see if the worker can accept worker. Should only be used in unit tests.
>     pub fn can_worker_accept_worker_for_test(&self, worker_id: &WorkerId) -> Result<bool, Error> {
> ```

I think you mean `can_worker_accept_work_for_test`? (ditto in comment on line above)
___
*[`native-link-scheduler/src/worker_scheduler.rs` line 62 at r5](https://reviewable.io/reviews/TraceMachina/native-link/413#-Nka73BdAwN7x7dqBnnm:-Nka73BdAwN7x7dqBnnn:bbc7vqe) ([raw file](https://github.com/TraceMachina/native-link/blob/d0f44b31d17a2e5a61c8a73c3e617f3c089899c1/native-link-scheduler/src/worker_scheduler.rs#L62)):*
> ```XML
>     async fn remove_timedout_workers(&self, now_timestamp: WorkerTimestamp) -> Result<(), Error>;
> 
>     /// Drains a worker from the pool and reschedule any tasks that might be running on it.
> ```

nit: Comment is now wrong.
___
*[`native-link-scheduler/src/worker_scheduler.rs` line 63 at r5](https://reviewable.io/reviews/TraceMachina/native-link/413#-NkaBJ1M-iQR3I01LDmq:-NkaBJ1M-iQR3I01LDmr:b-rzpbyb) ([raw file](https://github.com/TraceMachina/native-link/blob/d0f44b31d17a2e5a61c8a73c3e617f3c089899c1/native-link-scheduler/src/worker_scheduler.rs#L63)):*
> ```XML
> 
>     /// Drains a worker from the pool and reschedule any tasks that might be running on it.
>     async fn drain_worker(&self, worker_id: WorkerId) -> Result<(), Error>;
> ```

nit: Lets make this `set_drain_worker()` that takes a bool.
___
*[`native-link-scheduler/tests/simple_scheduler_test.rs` line 367 at r5](https://reviewable.io/reviews/TraceMachina/native-link/413#-NkaC7DfB5ROtASENCkP:-NkaC7DfB5ROtASENCkQ:bat3901) ([raw file](https://github.com/TraceMachina/native-link/blob/d0f44b31d17a2e5a61c8a73c3e617f3c089899c1/native-link-scheduler/tests/simple_scheduler_test.rs#L367)):*
> ```XML
>         let mut rx_from_worker1 = setup_new_worker(&scheduler, WORKER_ID1, PlatformProperties::default()).await?;
>         let insert_timestamp1 = make_system_time(1);
>         let mut client_rx1 = setup_action(
> ```

nit: Lets have the test do the following instead:
* Worker connects
* Sends a task to worker and ensure it accepts the task
* Complete the task
* Flag the worker as draining
* Send same task
* Ensure the task is now queued
* Set worker as no longer draining again
* Ensure task is now executing
___
*[`src/bin/cas.rs` line 407 at r5](https://reviewable.io/reviews/TraceMachina/native-link/413#-NkaBTdS4Yyh080xJtw0:-Nka9B0W5iarko47D1wc:b9450es) ([raw file](https://github.com/TraceMachina/native-link/blob/d0f44b31d17a2e5a61c8a73c3e617f3c089899c1/src/bin/cas.rs#L407)):*
> ```XML
>                 path,
>                 Router::new().route(
>                     "/scheduler/:instance_name/drain/:worker_id",
> ```

nit: Lets make this `set_drain_worker` with a 1 or 0 value after worker.
___
*[`src/bin/cas.rs` line 408 at r5](https://reviewable.io/reviews/TraceMachina/native-link/413#-Nka9W_tD7Kwl5iNN8lx:-Nka9W_tD7Kwl5iNN8ly:bew8o8q) ([raw file](https://github.com/TraceMachina/native-link/blob/d0f44b31d17a2e5a61c8a73c3e617f3c089899c1/src/bin/cas.rs#L408)):*
> ```XML
>                 Router::new().route(
>                     "/scheduler/:instance_name/drain/:worker_id",
>                     axum::routing::post(move |axum::extract::Path((instance_name, worker_id)): axum::extract::Path<(String, String)>| async move {
> ```

nit: This is confusing and ugly, can we have it pass in a generic variable, and extract it on the next line?
___
*[`src/bin/cas.rs` line 410 at r5](https://reviewable.io/reviews/TraceMachina/native-link/413#-Nka9nKS54pNrGVtsvY_:-Nka9nKS54pNrGVtsvYa:b-gy713p) ([raw file](https://github.com/TraceMachina/native-link/blob/d0f44b31d17a2e5a61c8a73c3e617f3c089899c1/src/bin/cas.rs#L410)):*
> ```XML
>                     axum::routing::post(move |axum::extract::Path((instance_name, worker_id)): axum::extract::Path<(String, String)>| async move {
>                         spawn(async move {
>                             (async move {
> ```

nit: No need for two async functions here, use just one then use `.and_then()` or `.map()` or similar functions on the future to do your modifications you need.
___
*[`src/bin/cas.rs` line 430 at r5](https://reviewable.io/reviews/TraceMachina/native-link/413#-Nka2cys5xoNKO_H1Bal:-Nka7glf2Fwyp3HuU9IA:bemse57) ([raw file](https://github.com/TraceMachina/native-link/blob/d0f44b31d17a2e5a61c8a73c3e617f3c089899c1/src/bin/cas.rs#L430)):*
<details><summary><i>Previously, steed924 (Steed) wrote…</i></summary><blockquote>

The reason I use unwrap()  here is because the post handler needs to return Response, not Result type.
That unwrap() is from Response::builder() and it won't cause a panic in normal cases I think.
Anyhow, I hope to have a great solution to handle this properly.

I handled other errors and made them to be returned in 500 error.
</blockquote></details>

We can't use `.unwrap()` pretty much anywhere in the code because it can cause panics, which are very bad and cause unexpected behavior. This is why we always use `Result<_, Error>` and propagate them up when needed.

In this case try using `.and_then()` instead of `.map()`.
___
*[`src/bin/cas.rs` line 438 at r5](https://reviewable.io/reviews/TraceMachina/native-link/413#-Nka8tRD5WpfJBVUe9Fn:-Nka8tRE2AtKVCZbJx1E:b-kk4pf6) ([raw file](https://github.com/TraceMachina/native-link/blob/d0f44b31d17a2e5a61c8a73c3e617f3c089899c1/src/bin/cas.rs#L438)):*
> ```XML
>                                     .status(500)
>                                     .body(Body::from(format!("{e:?}")))
>                                     .unwrap()
> ```

ditto, cannot use unwrap.
___
*[`src/bin/cas.rs` line 446 at r5](https://reviewable.io/reviews/TraceMachina/native-link/413#-Nka8v0r2dP3jmaGOt14:-Nka8v0r2dP3jmaGOt15:b-kk4pf6) ([raw file](https://github.com/TraceMachina/native-link/blob/d0f44b31d17a2e5a61c8a73c3e617f3c089899c1/src/bin/cas.rs#L446)):*
> ```XML
>                                 .status(500)
>                                 .body(Body::from(format!("{e:?}") [...]

2023-12-05 09:40 UTC, steed924 reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/native-link/413)* status: 6 of 16 files reviewed, 4 unresolved discussions (waiting on @allada)

___
*[`native-link-scheduler/src/simple_scheduler.rs` line 695 at r5](https://reviewable.io/reviews/TraceMachina/native-link/413#-Nka63au6VDQPqFzUiJ-:-NktLHAK1P8Aq-ejibaq:b-896fix) ([raw file](https://github.com/TraceMachina/native-link/blob/d0f44b31d17a2e5a61c8a73c3e617f3c089899c1/native-link-scheduler/src/simple_scheduler.rs#L695)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

I think you mean `can_worker_accept_work_for_test`? (ditto in comment on line above)
</blockquote></details>

Done.
___
*[`src/bin/cas.rs` line 438 at r5](https://reviewable.io/reviews/TraceMachina/native-link/413#-Nka8tRD5WpfJBVUe9Fn:-NktLQ5IDfRyzSVbr0mm:b-896fix) ([raw file](https://github.com/TraceMachina/native-link/blob/d0f44b31d17a2e5a61c8a73c3e617f3c089899c1/src/bin/cas.rs#L438)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

ditto, cannot use unwrap.
</blockquote></details>

Done.
___
*[`src/bin/cas.rs` line 446 at r5](https://reviewable.io/reviews/TraceMachina/native-link/413#-Nka8v0r2dP3jmaGOt14:-NktLQZ3EBD7DfSy-Pkk:b-896fix) ([raw file](https://github.com/TraceMachina/native-link/blob/d0f44b31d17a2e5a61c8a73c3e617f3c089899c1/src/bin/cas.rs#L446)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

ditto, cannot use unwrap.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-12-05 18:57 UTC, steed924 reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/native-link/413)* status: 13 of 16 files reviewed, 1 unresolved discussion (waiting on @allada)

___
*[`native-link-scheduler/src/simple_scheduler.rs` line 396 at r7](https://reviewable.io/reviews/TraceMachina/native-link/413#-NkulGiHBJ7aNMEzsJn_:-NkvKft1DhPV5FDlUjF3:b6xzgry) ([raw file](https://github.com/TraceMachina/native-link/blob/1e10aeb16a1c1b936307f8b6ad50ab5d98f7e449/native-link-scheduler/src/simple_scheduler.rs#L396)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: We don't need to trigger this any more.
</blockquote></details>

Hmm, I think we need this. I have removed this and ran test but it failed. I think it tells the loop the worker's state has changed and allows the scheduler to reschedule jobs when needed.


<!-- Sent from Reviewable.io -->

2023-12-05 19:46 UTC, allada reviewed
> Reviewed 3 of 3 files at r8.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/native-link/413)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @steed924)

___
*[`native-link-scheduler/src/simple_scheduler.rs` line 396 at r7](https://reviewable.io/reviews/TraceMachina/native-link/413#-NkulGiHBJ7aNMEzsJn_:-NkvVzer6GxUkebwRYRb:bbh8nkf) ([raw file](https://github.com/TraceMachina/native-link/blob/1e10aeb16a1c1b936307f8b6ad50ab5d98f7e449/native-link-scheduler/src/simple_scheduler.rs#L396)):*
<details><summary><i>Previously, steed924 (Steed) wrote…</i></summary><blockquote>

Hmm, I think we need this. I have removed this and ran test but it failed. I think it tells the loop the worker's state has changed and allows the scheduler to reschedule jobs when needed.
</blockquote></details>

Aaah, you are right. Good catch :-)
___
*[`native-link-scheduler/tests/simple_scheduler_test.rs` line 388 at r8](https://reviewable.io/reviews/TraceMachina/native-link/413#-NkvW6nVEKUwMQ2X70Uz:-NkvW6nVEKUwMQ2X70V-:blfhosd) ([raw file](https://github.com/TraceMachina/native-link/blob/72429dd9bd2abe6ca820f3a202edc04b4812d461/native-link-scheduler/tests/simple_scheduler_test.rs#L388)):*
> ```XML
>         };
> 
>         let action_result = ActionResult {
> ```

nit: You don't need any of this either.


<!-- Sent from Reviewable.io -->

2023-12-05 20:54 UTC, allada approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/native-link/413#-:-NkvkjXu-vpkKVBK90Lu:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @steed924)



<!-- Sent from Reviewable.io -->

2023-12-05 20:55 UTC, merged