Fixed error forwarding to client for failed command executions
TraceMachina/native-link pull request #432
Opened 2023-12-01 01:50 UTC by TripleKai

# Description

Added error forwarding to client upon any command execution failures. Interrupts client hang and displays the forwarded error.

Fixes #257

## Type of change

- [ ] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Tested with plain bazel test //... to ensure all pass as well as bazel test //... after adding deliberate modifications to deployment-examples/docker-compose/worker.json to ensure error forwarding to client (ex. "entrypoint_cmd": "foo").

## Checklist

- [ ] Updated documentation if needed
- [ ] Tests added/amended
- [ ] `bazel test //...`  passes locally
- [ ] PR is contained in a single commit, using `git amend` see some [docs](https://www.atlassian.com/git/tutorials/rewriting-history)

2023-12-01 06:36 UTC, MarcusSorealheis reviewed
There are two small concerns 

First, it would be great if you could amend this commit, `git commit --amend`, and force push a test, `git push -f`. The reason for it is we need to have regression detection in pace specifically for this bug. It was a tricky one for a first contribution, especially when new to Rust, so I commend you. 

The second thing is a nit:

I would change the commit message to Fixes because this code lives on. Also, in the PR description, is "displays" the correct word?

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/native-link/432#-:-NkYkh7A1etuCCjU4GnJ:b-cyim3m)* status: 0 of 1 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-12-01 06:37 UTC, MarcusSorealheis requested changes
note (I'm still ramping on Reviewable myself some days): Needs tests

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/native-link/432#-:-NkZ51Bw5PlF1uUcxcuL:bby203z)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @TripleKai)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/TraceMachina/native-link/432#-NkZ4xiwCHyIOBiZ7Xkg):*
nit: Fixes


<!-- Sent from Reviewable.io -->

2023-12-01 16:04 UTC, TripleKai commented
Sounds good, I'll make those changes for the commit and reword the description to something like "Added error forwarding to client upon any command execution failures. Allows proper error workflow to complete for internal errors."





<!-- Sent from Reviewable.io -->

2023-12-01 16:06 UTC, TripleKai commented
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

We need a test for this. @TripleKai , do you want to take a swing at making a test for it?
</blockquote></details>

Sure thing, I'll give it a try




<!-- Sent from Reviewable.io -->

2023-12-01 16:29 UTC, TripleKai commented
And thanks for the praise, I'm glad I could contribute!





<!-- Sent from Reviewable.io -->

2023-12-06 21:56 UTC, allada approved these changes
Awesome, good job. Just some minor nits and <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/native-link/432#-:-Nl07WK58D7Em2L6XDnt:b-qvs8pm)* status: all files reviewed, 5 unresolved discussions (waiting on @blakehatch and @TripleKai)

___
*[`native-link-scheduler/tests/simple_scheduler_test.rs` line 1409 at r2](https://reviewable.io/reviews/TraceMachina/native-link/432#-Nl05qRTDmfb0E5k9XFk:-Nl05qRTDmfb0E5k9XFl:b2l3080) ([raw file](https://github.com/TraceMachina/native-link/blob/5f1862865a2e7fac06063e4d001d77e48e6b488b/native-link-scheduler/tests/simple_scheduler_test.rs#L1409)):*
> ```XML
> 
>     #[tokio::test]
>     async fn ensure_task_or_worker_change_notification_received_test() -> Result<(), Error> {
> ```

nit: Please add a comment above referencing the ticket this regression test is checking.
___
*[`native-link-scheduler/tests/simple_scheduler_test.rs` line 1420 at r2](https://reviewable.io/reviews/TraceMachina/native-link/432#-Nl06pfHATiBgsRpe91o:-Nl06pfHATiBgsRpe91p:bv4xdlv) ([raw file](https://github.com/TraceMachina/native-link/blob/5f1862865a2e7fac06063e4d001d77e48e6b488b/native-link-scheduler/tests/simple_scheduler_test.rs#L1420)):*
> ```XML
> 
>         let mut rx_from_worker1 = setup_new_worker(&scheduler, WORKER_ID1, PlatformProperties::default()).await?;
>         let insert_timestamp = make_system_time(1);
> ```

nit: inline this.
___
*[`native-link-scheduler/tests/simple_scheduler_test.rs` line 1441 at r2](https://reviewable.io/reviews/TraceMachina/native-link/432#-Nl079zLBjb_4fMqXe64:-Nl079zLBjb_4fMqXe65:bv4xdlv) ([raw file](https://github.com/TraceMachina/native-link/blob/5f1862865a2e7fac06063e4d001d77e48e6b488b/native-link-scheduler/tests/simple_scheduler_test.rs#L1441)):*
> ```XML
>         }
> 
>         let action_info_hash_key = ActionInfoHashKey {
> ```

nit: inline this.
___
*[`native-link-scheduler/tests/simple_scheduler_test.rs` line 1459 at r2](https://reviewable.io/reviews/TraceMachina/native-link/432#-Nl07HkUCDqB7lwsR2MA:-Nl07HkUCDqB7lwsR2MB:b3w72fi) ([raw file](https://github.com/TraceMachina/native-link/blob/5f1862865a2e7fac06063e4d001d77e48e6b488b/native-link-scheduler/tests/simple_scheduler_test.rs#L1459)):*
> ```XML
>         {
>             // Other tests check full data. We only care if we got StartAction.
>             match rx_from_worker2.recv().await.unwrap().update {
> ```

Nit: use `?`



_Code quote:_
```XML
.unwrap()
```


<!-- Sent from Reviewable.io -->

2023-12-06 22:53 UTC, TripleKai commented
Sure thing, will do





<!-- Sent from Reviewable.io -->

2023-12-07 00:00 UTC, TripleKai commented
*[`native-link-scheduler/tests/simple_scheduler_test.rs` line 1459 at r2](https://reviewable.io/reviews/TraceMachina/native-link/432#-Nl07HkUCDqB7lwsR2MA:-Nl0YUgU90QZozUqsjFK:b-a2ms37) ([raw file](https://github.com/TraceMachina/native-link/blob/5f1862865a2e7fac06063e4d001d77e48e6b488b/native-link-scheduler/tests/simple_scheduler_test.rs#L1459)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

Nit: use `?`
</blockquote></details>

I tried converting the whole "match" expression into something like "rx_from_worker2.recv().await?.update;"
but this doesn't work because "recv()" returns an Option and our test function returns a Result, so I see a complaint when trying to use "?". Am I misusing this "?" operator?


<!-- Sent from Reviewable.io -->

2023-12-07 15:41 UTC, allada approved these changes
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/native-link/432)* status: all files reviewed, 5 unresolved discussions (waiting on @blakehatch and @TripleKai)

___
*[`native-link-scheduler/tests/simple_scheduler_test.rs` line 1459 at r2](https://reviewable.io/reviews/TraceMachina/native-link/432#-Nl07HkUCDqB7lwsR2MA:-Nl3w6QN3vlhf4RNYG3q:blc5bo4) ([raw file](https://github.com/TraceMachina/native-link/blob/5f1862865a2e7fac06063e4d001d77e48e6b488b/native-link-scheduler/tests/simple_scheduler_test.rs#L1459)):*
<details><summary><i>Previously, TripleKai (Kailash Saravanan) wrote…</i></summary><blockquote>

I tried converting the whole "match" expression into something like "rx_from_worker2.recv().await?.update;"
but this doesn't work because "recv()" returns an Option and our test function returns a Result, so I see a complaint when trying to use "?". Am I misusing this "?" operator?
</blockquote></details>

try:
```rs
.er_tip(|| "worker went away")?
```


<!-- Sent from Reviewable.io -->

2023-12-07 18:16 UTC, allada approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/native-link/432)* status: all files reviewed, 1 unresolved discussion (waiting on @blakehatch and @TripleKai)



<!-- Sent from Reviewable.io -->

2023-12-07 18:58 UTC, adam-singer approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/native-link/432#-:-Nl4dL_856HCzlKGxhEL:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @blakehatch and @TripleKai)



<!-- Sent from Reviewable.io -->

2023-12-07 21:43 UTC, TripleKai commented
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/TraceMachina/native-link/432#-NkZ4xiwCHyIOBiZ7Xkg):*
<details><summary><i>Previously, MarcusSorealheis (Marcus Eagan) wrote…</i></summary><blockquote>

nit: Fixes
</blockquote></details>

Just commenting here to mention this is done


<!-- Sent from Reviewable.io -->

2023-12-08 04:05 UTC, merged

2023-12-08 05:37 UTC, MarcusSorealheis commented
Amazing!